[package]
name = "pdf-test"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-rs = { version = "0.9.1", features = ["png", "pdf"] }
poppler = { git = "https://github.com/danielzfranklin/poppler-rs" }
